### ISSUE TITLE
Entering the Age of Tightly Coupled Fullstack Web Development with Universal Data Model with Falcor

### ISSUE THREAD

**Issue by d6u** [NodeDC/talks#1]
## Your name

Daiwei Lu
## Your idea

I want to talk about the new frontier of interactions between frontend single page application and backend server. Specifically about:
- React.js server rendering
  - Basic setup with Express.js
  - Routing in both frontend and backend
  - How to use webpack to work with universal JavaScript code
  - What's the impact on UX?
- One model over everything approach of modeling data with Falcor
  - What is it?
  - Why we need it?
  - How to setup with Express.js

I learned some of those while building https://github.com/TryStarboard/Starboard/
## Approx length

prefer to be 40min, but I can compress it into about 25min.

**Comment by danmactough** [comment]
![image](https://cloud.githubusercontent.com/assets/357481/13091855/0295ac02-d4cb-11e5-8c9c-ef4584e4ae90.png)

:sob: 

---

The React and Falcor pieces being part of the same talk seems like a **LOT** of ground to cover. Have you presented this before or do you have a good idea you can cover all this in 40 minutes?

**Comment by d6u** [comment]
@danmactough Thanks for checking out :+1:. I will fix this when I got time, consider this is pre-alpha :laughing:. 

I won't use this as a demo in the talk though. It will be a much simpler "hello world" kind demo.

---

The idea is to gently let people know
- Why coupling can be a good idea when everybody else is decoupled with REST API
- What can be achieved using React server rendering and Falcor

It will be overview focused and not trying to pay too much attention to the details of usage of all the APIs. That's said, if we feels like there is too much stuff, we can just do React server rendering and be more focused.

**Comment by JuanCaicedo** [comment]
^ that answers some of my questions! :smiley: 

I definitely don't want to hamper you from going into the advanced stuff! I would just be sad if some more beginner level attendees felt lost/overwhelmed. I think the idea of just focusing on React and server rendering sounds good, if you think you could still show what you want to show without going much into Falcor

**Comment by danmactough** [comment]
> I think the idea of just focusing on React and server rendering sounds good, if you think you could still show what you want to show without going much into Falcor

I was kind of thinking the opposite! Maybe focusing more on Falcor and tightly coupling your data, less about the tight-coupling of code with isomorphic/universal javascript. Hmm...

If you can get through explaining "what is Falcor" in like 2 minutes or less to get to the crux of your idea, then maybe the scope is fine as you've presented it.

**Comment by d6u** [comment]
I like the idea of just doing Falcor, since not everyone can use React if they are already on some framework and not everybody would do server rendering. But a modeling solution would be useful to most people regardless of what frontend framework to use.

I'm not confident on that I can explaining "what is Falcor" clearly in 2min. So let's say I propose to just talk about Falcor + Express + maybe jQuery.

**Comment by JuanCaicedo** [comment]
SGTM!

**Comment by d6u** [comment]
@danmactough, a bit off topic. But could you try http://www.getstarboard.xyz/ again when you have time? I added some logging. Really want to know why it didn't work for you. Thanks.

**Comment by danmactough** [comment]
@d6u :smile: done

**Comment by d6u** [comment]
@danmactough Thanks a lot! Found the problem! In case you interested:

```
Cannot read property '0' of undefined
/source/server/util/auth/githubStrategy.js in Strategy.<anonymous> at line 26
```

**Comment by danmactough** [comment]
that dang `undefined`

**Comment by d6u** [comment]
The error was fixed :tada: 

![starboard-demo](https://cloud.githubusercontent.com/assets/2153667/13125983/7f1ffa9a-d596-11e5-9386-c584ff33ae36.gif)

**Comment by danmactough** [comment]
@d6u Is this superceded by #3 or do you have another talk, here?

**Comment by d6u** [comment]
Yes, I will close this, thanks!
