### ISSUE TITLE
"Server rendering your single page app with React.js for better UX"

### ISSUE THREAD

**Issue by d6u** [NodeDC/talks#3]
**Your name:** Daiwei Lu

**Title:** Server rendering your single page app with React.js for better UX

**Agenda:**
1. UX challenge when building a single page web app
2. How server rendering impacts UX? (live demo)
3. How to do it? (coding demo)
4. The caveat: routing, data model, performance, complexity of setup.
5. Share some resources to move forward from here.

**Approx length:** 30min

**Comment by d6u** [comment]
@JuanCaicedo

**Comment by JuanCaicedo** [comment]
@d6u accepted in #46, looking forward to hearing this talk!

**Comment by danmactough** [comment]
this happened! - https://www.meetup.com/node-dc/events/231253851/
