### ISSUE TITLE
Building an Amazon Echo Skill

### ISSUE THREAD

**Issue by jakerella** [NodeDC/talks#5]
## Talk Proposal Template

**Your name:** Jordan Kasper

**Your idea:** Building an Amazon Echo skill is extremely simple, if a bit cumbersome. If you're not familiar, the Echo is an always-on home automation unit that allows developers to extend its functionality with "skills". These skills get the benefit of Amazon's full speech analysis engine and work through a simple JSON web API. In this talk I'll cover how we can use Node.js to write the skill (a small web app) and what else we need to do to get up and running. You don't need to own an Echo to write a skill... although they sure are fun to play with!

**Approx length:** Probably a full-session talk (45 minutes or so). I could cut this down to a smaller slot if necessary though.

I'd be available any month except September.

**Comment by danmactough** [comment]
@jakerella 7/21? 😁

**Comment by jakerella** [comment]
Sigh... I might be able to. I don't have much time to prep. I don't actually have a "talk" on this. I've just done it, so I could talk about it. If you _really_ need me to I can... but I'd prefer to have more time to prep.

**Comment by danmactough** [comment]
Ok, @jakerella. Let's pencil this for August 18, then.

**Comment by jakerella** [comment]
Sweet. I'm down for that.

**Comment by danmactough** [comment]
👍

**Comment by jakerella** [comment]
We on for August? Want to put this on the calendar if so... but I'm also cool with doing this later if you have something else coming in.

**Comment by danmactough** [comment]
> We on for August? Want to put this on the calendar if so... but I'm also cool with doing this later if you have something else coming in.

Yeah, I think so. If we do #6, it would be in addition to your talk on 8/18.

**Comment by jakerella** [comment]
Cool... looks like you were targeting 9/1 for #6 though? FYI, my content can easily fill a full talk. I can most likely fit it into 40 minutes... 30 minutes would be tight, but possible.

**Comment by danmactough** [comment]
Sorry. I was unclear. I meant to say: If we do #6 on 9/1, it would be in addition to your talk on 8/18. 😄

**Comment by jakerella** [comment]
Aaaah. Coolio.

**Comment by danmactough** [comment]
@jakerella Is this part of your talk? [alexa/alexa-skills-kit-sdk-for-nodejs](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs)

**Comment by jakerella** [comment]
I'm going to mention it... but that sdk is only for running on Lambda, which I do not. I'll be coming at it from a much more generic perspective.

**Comment by danmactough** [comment]
Cool 😎

**Comment by jakerella** [comment]
🍆

**Comment by danmactough** [comment]
this happened - https://www.meetup.com/node-dc/events/233285730/
